### ISSUE TITLE
Question about pYin

### ISSUE THREAD

**Issue by Charlottecuc** [sannawag/autotuner#10]
Hi. I extracted the pYin of `survive_4_vocals.wav` by using Sonic Visualizer (transform->pYin->notes). The resulting csv file is like this:
![Screenshot 2021-03-11 at 6 01 22 PM](https://user-images.githubusercontent.com/43811904/110770115-e5ac2680-8293-11eb-8d1f-1399c75a2c01.png)

However, I only got 136 rows, while in your `survive_4_vocals.csv`, there are 138 rows.

And, when I tried to auto-tune the model by `python rnn.py --use_combination_channel True  --extension "3" --resume True --run_training False --run_autotune True`, the following error occurred:

`exception in dataset index 1943 is out of bounds for axis 0 with size 1813 Traceback (most recent call last):
  File "rnn.py", line 336, in __getitem__
    data_dict = self.getitem_realworld_cqt(idx)
  File "rnn.py", line 182, in getitem_realworld_cqt
    original_boundaries = np.array([original_boundaries[notes[:, 0]], original_boundaries[notes[:, 1]]]).T
IndexError: index 1943 is out of bounds for axis 0 with size 1813
 skipping song survive_4_vocals`

Could you tell me how do you extract pYin from wav files (e.g. parameters in Sonic Annotator), and how to avoid above error? 
Thank you very much.

**Comment by suzhenghang** [comment]
@Charlottecuc  have you solved this problem? by the way, could you share your parameters in Sonic Annotator? I only could get two column.

**Comment by evi-Genius** [comment]
I get the same issus, have you solve the problem?
