### ISSUE TITLE
New audio sample

### ISSUE THREAD

**Issue by WindowsNT** [sannawag/autotuner#11]
This is interesting, I tried to build it and done it with some hassle (using import soundfile, some type conversions), then injected a new file into training_data\raw_audio\vocal_tracks as survive_4_vocals.wav, then

`python rnn.py --extension "3"  --run_training True --run_autotune False`

then 

`python rnn.py --extension "3"  --run_training False --run_autotune True`

then 
```
exception in dataset index 61 is out of bounds for axis 0 with size 18 Traceback (most recent call last):
  File "G:\wp1\PitchCorrection\rnn.py", line 332, in __getitem__
    data_dict = self.getitem_realworld_cqt(idx)
  File "G:\wp1\PitchCorrection\rnn.py", line 178, in getitem_realworld_cqt
    original_boundaries = np.array([original_boundaries[notes[:, 0]], original_boundaries[notes[:, 1]]]).T
IndexError: index 61 is out of bounds for axis 0 with size 18


```

I'm a C++ developer so my Python knowledge is limited, perhaps this has to do with plotting.
I' d appreciate if you give me more specific directions.

**Comment by sannawag** [comment]
Did you use your own data? If so, the first question that comes to mind is whether you used the same hop size for pYIN as what is set in globals.py.

Otherwise, would you mind printing the shapes of the various arrays involved? Thanks!
